project:
  type: book
  output-dir: docs

book:
  title: "Debugging in R"
  author: "Elise Hellwig"
  date: "November, 15 2023"
  
  search: true
  repo-url: https://github.com/d-rug/debugging_in_R
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_tasks.qmd
    - 03_example.qmd
  
  sidebar:
    logo: https://github.com/d-rug/d-rug.github.io/raw/main/DRUG_final_cobalt.png
  site-url: https://d-rug.github.io

format:
  html:
    theme: cosmo
    number-sections: false